name: Deploy Flask App

on:
  push:
    branches:
      - master  # Trigger on push to master branch
  workflow_dispatch:  # You can manually trigger the workflow from GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask App (test deployment)
        run: |
          python app.py

      - name: Deploy to Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku login -i
          heroku create your-app-name
          git push heroku master
